[debug] [2025-05-24T05:22:31.009Z] ----------------------------------------------------------------------
[debug] [2025-05-24T05:22:31.013Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\balav\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-05-24T05:22:31.014Z] CLI Version:   14.4.0
[debug] [2025-05-24T05:22:31.014Z] Platform:      win32
[debug] [2025-05-24T05:22:31.014Z] Node Version:  v22.12.0
[debug] [2025-05-24T05:22:31.015Z] Time:          Sat May 24 2025 10:52:31 GMT+0530 (India Standard Time)
[debug] [2025-05-24T05:22:31.015Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as balavignesh043@gmail.com
[debug] [2025-05-24T05:22:41.374Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\balav\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:267:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-05-24T05:23:45.263Z] ----------------------------------------------------------------------
[debug] [2025-05-24T05:23:45.267Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\balav\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2025-05-24T05:23:45.267Z] CLI Version:   14.4.0
[debug] [2025-05-24T05:23:45.268Z] Platform:      win32
[debug] [2025-05-24T05:23:45.268Z] Node Version:  v22.12.0
[debug] [2025-05-24T05:23:45.268Z] Time:          Sat May 24 2025 10:53:45 GMT+0530 (India Standard Time)
[debug] [2025-05-24T05:23:45.268Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-05-24T05:23:45.551Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-05-24T05:23:45.552Z] > authorizing via signed-in user (balavignesh043@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  D:\React youtube\my-youtube

Before we get started, keep in mind:

  * You are initializing within an existing Firebase project directory

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2025-05-24T05:23:56.028Z] Using project from CLI flag: netflix-gpt-043
[debug] [2025-05-24T05:23:56.029Z] Checked if tokens are valid: true, expires at: 1748067441995
[debug] [2025-05-24T05:23:56.029Z] Checked if tokens are valid: true, expires at: 1748067441995
[debug] [2025-05-24T05:23:56.031Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/netflix-gpt-043 [none]
[debug] [2025-05-24T05:24:17.155Z] *** [apiv2] error from fetch(https://firebase.googleapis.com/v1beta1/projects/netflix-gpt-043, {"headers":{},"method":"GET","signal":{}}): FetchError: request to https://firebase.googleapis.com/v1beta1/projects/netflix-gpt-043 failed, reason: connect ETIMEDOUT 2404:6800:4007:80d::200a:443
[debug] [2025-05-24T05:24:17.156Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/netflix-gpt-043 (original: request to https://firebase.googleapis.com/v1beta1/projects/netflix-gpt-043 failed, reason: connect ETIMEDOUT 2404:6800:4007:80d::200a:443)
[debug] [2025-05-24T05:24:22.171Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\balav\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:267:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
